#https://www.home-assistant.io/lovelace/
####################################################
#                                                  #
#                      HOME                        #
#                                                  #
####################################################

resources:
  - url: /community_plugin/weather-card/weather-card.js
    type: module
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/bar-card/bar-card.js
    type: js
  - url: /community_plugin/mini-graph-card/mini-graph-card.js
    type: module
  - url: /community_plugin/mini-media-player/mini-media-player.js
    type: module
  - url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
    type: module
  - url: /community_plugin/simple-thermostat/simple-thermostat.js
    type: module
  - url: /community_plugin/lovelace-home-feed-card/home-feed-card.js
    type: js
  - url: /community_plugin/surveillance-card/surveillance-card.js
    type: module
  - url: /community_plugin/lovelace-card-mod/card-mod.js
    type: js
  - url: /community_plugin/content-card-remote-control/content-card-remote-control.js
    type: js
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module
  - url: /community_plugin/github-card/github-card.js
    type: js
  - url: /community_plugin/lovelace-layout-card/layout-card.js
    type: js
  - url: /community_plugin/lovelace-auto-entities/auto-entities.js
    type: js
  - url: /community_plugin/lovelace-card-tools/card-tools.js
    type: js
  - url: /community_plugin/list-card/list-card.js
    type: js

title: My Awesome Home
views:
  - !include lovelace/00_home_view.yaml
  - !include lovelace/10_sicurezza_view.yaml
  - !include lovelace/20_camere_view.yaml
  - !include lovelace/30_floorplan_view.yaml
  - !include lovelace/40_system_view.yaml
  - !include lovelace/50_info_view.yaml
  - !include lovelace/60_luci_view.yaml
  - !include lovelace/70_energia_view.yaml
  - !include lovelace/75_parametri_view.yaml
  - !include lovelace/80_sensori_view.yaml
  - !include lovelace/90_backup_view.yaml
  - !include lovelace/91_docker_view.yaml
  - !include lovelace/95_news_view.yaml
  - !include lovelace/100_clima_view.yaml
  - !include lovelace/110_meteo_view.yaml
  - !include lovelace/120_notification_view.yaml
#  - !include lovelace/121_differenziata_view.yaml
  - !include lovelace/130_multimedia_view.yaml
 
####################################################
#                                                  #
#                 NEWS & Grafici                   #
#                                                  #
####################################################
#  - icon: mdi:chart-areaspline
#    title: Grafici
#    path: grafici
#    cards:
##1 colonna


####################################################
#                                                  #
#                     FINE                         #
#                                                  #
####################################################
