#################################################################
#                                                               #
#                       Packages/Presence                       #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'youtube'
        version: '0.1'
        author: 'Gianpi - www.hassiohelp.eu'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

#################################################################
#                                                               #
#                           Sensori                             #
#                                                               #
################################################################# 
sensor:
  platform: youtube
  channel_id: UCX2Vhc0LIzSS9aMzhGFZ7PA
  
#################################################################
#                                                               #
#                             END                               #
#                                                               #
#################################################################